<template>
  <div class="biba">
    Hello nigga

    <ComponentOne />
    <ComponentOne />
    <ComponentOne />
    <ComponentOne />
    <ComponentOne />
    <ComponentOne />
    <ComponentOne />
    <ComponentOne />
    <ComponentOne />
    <ComponentOne />
    <ComponentOne />
    <ComponentOne />
    <ComponentOne />
    <ComponentOne />
    <ComponentOne />
    <ComponentOne />
    <ComponentOne />
    <ComponentOne />
    <ComponentOne />
    <ComponentOne />
    <ComponentOne />
    <ComponentOne />
    <ComponentOne />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
    <ComponentTwo />
  </div>
</template>

<script>
import ComponentTwo from './components/ComponentTwo.vue'
import ComponentOne from './components/ComponentOne.vue'

export default {
  components: {
    ComponentTwo,
    ComponentOne
  }
}
</script>
